version: '3.8'

services:
  api:
    container_name: server-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    env_file: .env.dev
    environment: 
      - NODE_ENV=dev
    ports:
      - ${PORT}:${PORT}
      - 9222:9229
    networks:
      - marvelovers-net
    depends_on:
      - mariadb
    command: NODE_ENV=dev npm run start:debug
      
  mariadb:
    container_name: db-dev
    image: mariadb:10.5.3-focal
    env_file: .env.dev
    restart: always
    networks:
      - marvelovers-net
    environment:
      TZ: 'America/Bahia'
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - 3309:${DB_PORT}
    volumes:
      - dbdata:/var/lib/mysql

networks:
  marvelovers-net:
volumes:
  dbdata:
